use axum::extract::State;
use axum::routing::post;
use axum::{Json, Router};
use axum_extra::extract::cookie::PrivateCookieJar;
use serde::{Deserialize, Serialize};

use crate::auth::{current_user, ensure_fresh_token};
use crate::embeddings;
use crate::error::{AppError, AppResult};
use crate::library::{ensure_user_library, TrackLite};
use crate::AppState;

const SPOTIFY_API: &str = "https://api.spotify.com/v1";

pub fn router() -> Router<AppState> {
    Router::new()
        .route("/playlists/generate", post(generate))
        .route("/playlists/save", post(save))
}

#[derive(Debug, Deserialize)]
pub struct GenerateRequest {
    pub vibe: String,
    #[serde(default = "default_limit")]
    pub limit: usize,
}

fn default_limit() -> usize {
    20
}

#[derive(Debug, Serialize)]
pub struct GeneratedPlaylist {
    pub vibe: String,
    pub model: String,
    pub considered: usize,
    pub items: Vec<RankedTrack>,
}

#[derive(Debug, Serialize)]
pub struct RankedTrack {
    pub id: String,
    pub name: String,
    pub artists: Vec<String>,
    pub album: String,
    pub image_url: Option<String>,
    pub score: f32,
}

async fn generate(
    State(state): State<AppState>,
    jar: PrivateCookieJar,
    Json(req): Json<GenerateRequest>,
) -> AppResult<Json<GeneratedPlaylist>> {
    if req.vibe.trim().is_empty() {
        return Err(AppError::Upstream("vibe is empty".into()));
    }

    let mut user = current_user(&state, &jar).await?;
    let lib = ensure_user_library(&state, &mut user).await?;
    let considered = lib.tracks.len();

    if considered == 0 {
        return Ok(Json(GeneratedPlaylist {
            vibe: req.vibe,
            model: lib.stored_model,
            considered: 0,
            items: vec![],
        }));
    }

    let prompt_resp = state.embedder.embed(&[req.vibe.clone()]).await?;
    let prompt_vec = prompt_resp
        .embeddings
        .into_iter()
        .next()
        .ok_or_else(|| AppError::Upstream("empty prompt embedding".into()))?;

    let mut scored: Vec<RankedTrack> = lib
        .tracks
        .iter()
        .filter_map(|t| {
            let id = t.id.as_ref()?;
            let emb = lib.embeddings.get(id)?;
            let score = embeddings::cosine(&prompt_vec, emb);
            Some(RankedTrack {
                id: id.clone(),
                name: t.name.clone(),
                artists: t.artists.iter().map(|a| a.name.clone()).collect(),
                album: t.album.name.clone(),
                image_url: t.album.images.first().map(|i| i.url.clone()),
                score,
            })
        })
        .collect();

    scored.sort_by(|a, b| {
        b.score
            .partial_cmp(&a.score)
            .unwrap_or(std::cmp::Ordering::Equal)
    });
    scored.truncate(req.limit.clamp(1, 100));

    Ok(Json(GeneratedPlaylist {
        vibe: req.vibe,
        model: lib.stored_model,
        considered,
        items: scored,
    }))
}

#[derive(Debug, Deserialize)]
pub struct SaveRequest {
    pub name: String,
    pub vibe: Option<String>,
    pub track_ids: Vec<String>,
    #[serde(default)]
    pub public: bool,
}

#[derive(Debug, Serialize)]
pub struct SaveResponse {
    pub playlist_id: String,
    pub url: String,
    pub name: String,
    pub track_count: usize,
}

#[derive(Debug, Deserialize)]
struct CreatedPlaylist {
    id: String,
    #[serde(default)]
    external_urls: Option<ExternalUrls>,
}

#[derive(Debug, Deserialize)]
struct ExternalUrls {
    #[serde(default)]
    spotify: Option<String>,
}

async fn save(
    State(state): State<AppState>,
    jar: PrivateCookieJar,
    Json(req): Json<SaveRequest>,
) -> AppResult<Json<SaveResponse>> {
    if req.name.trim().is_empty() {
        return Err(AppError::Upstream("name is empty".into()));
    }
    if req.track_ids.is_empty() {
        return Err(AppError::Upstream("no tracks to save".into()));
    }

    let mut user = current_user(&state, &jar).await?;
    let token = ensure_fresh_token(&state, &mut user).await?;

    let description = match req.vibe.as_deref() {
        Some(v) if !v.trim().is_empty() => format!(
            "Generated by spoti.phirios.com — vibe: {}",
            v.trim().chars().take(180).collect::<String>()
        ),
        _ => "Generated by spoti.phirios.com".into(),
    };

    let create_url = format!("{SPOTIFY_API}/users/{}/playlists", user.spotify_id);
    let create_body = serde_json::json!({
        "name": req.name,
        "description": description,
        "public": req.public,
    });
    let resp = state
        .http
        .post(&create_url)
        .bearer_auth(&token)
        .json(&create_body)
        .send()
        .await?;
    if !resp.status().is_success() {
        let s = resp.status();
        let body = resp.text().await.unwrap_or_default();
        return Err(AppError::Upstream(format!(
            "create playlist failed: {s}: {body}"
        )));
    }
    let created: CreatedPlaylist = resp.json().await?;

    let uris: Vec<String> = req
        .track_ids
        .iter()
        .map(|id| format!("spotify:track:{id}"))
        .collect();
    let add_url = format!("{SPOTIFY_API}/playlists/{}/tracks", created.id);
    for chunk in uris.chunks(100) {
        let body = serde_json::json!({ "uris": chunk });
        let resp = state
            .http
            .post(&add_url)
            .bearer_auth(&token)
            .json(&body)
            .send()
            .await?;
        if !resp.status().is_success() {
            let s = resp.status();
            let body = resp.text().await.unwrap_or_default();
            return Err(AppError::Upstream(format!(
                "add tracks failed: {s}: {body}"
            )));
        }
    }

    let url = created
        .external_urls
        .and_then(|u| u.spotify)
        .unwrap_or_else(|| format!("https://open.spotify.com/playlist/{}", created.id));

    Ok(Json(SaveResponse {
        playlist_id: created.id,
        url,
        name: req.name,
        track_count: uris.len(),
    }))
}

// Re-export so tests / callers don't need to import library directly.
#[allow(dead_code)]
pub type Track = TrackLite;
